name: Context testing
on: push

jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: function
        run: |
          echo ${{ contains( search, item ) }}
          echo ${{ contains( search, arc ) }}
          echo ${{ endsWith( search, rch ) }}
          echo ${{ startsWith( search, sea ) }}
          echo ${{ format('Hello {0} {1} {2}', 'World', '!', '!') }}
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'