name: Matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        node: [ 10, 12, 14 ]
    runs-on: ubuntu-latest
    steps:
      - name: Log node version
        run: node --version
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Log node version
        run: node -v